/*
 * Creche
 * Api for creche
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: uzairkamal@yahoo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.creche.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BabyApi
 */
@Ignore
public class BabyApiTest {

    private final BabyApi api = new BabyApi();

    
    /**
     * create request for baby
     *
     * Get Baby details for respective identifier.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBabyTest() {
        String id = "123";
        String requestId = "123";
        api.getBaby(id, requestId);

        // TODO: test validations
    }
    
}
